dubbo:
  application:
    name: shazam-dubbo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk
    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181